name: Build & Deploy May.la MyST
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3

    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt

    - name: Make
      run: |
        make html

#    - name: Upload Site
#      uses: SamKirkland/FTP-Deploy-Action@2.0.0
#      env:
#        FTP_SERVER: www456.your-server.de
#        FTP_USERNAME: eniaka_2
#        FTP_PASSWORD: ${{ secrets.MAY_LA_FTP_PWD }}
#        LOCAL_DIR: build/html
#        METHOD: sftp
#        PORT: 22
#        ARGS: --delete
